# This is a basic workflow to help you get started with Actions

name: SmartSeedRuntimeSpecialPointTests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ smartseedruntimetest-workflow ] # Temporarily change for testing
  pull_request:
    branches: [ smartseedruntimetest-workflow ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Setup JDK8 + JavaFX
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'zulu' # Zulu supports JavaFX, which Evosuite uses.
          java-package: 'jdk+fx'
  
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
  
      - name: Run tests with Maven
        run: mvn test -Dtest=SmartSeedRuntimeTest#testSpecialPoint* -DfailIfNoTests=false -Dsurefire.useFile=false
