# This is a basic workflow to help you get started with Actions

name: SmartSeedRuntimeSpecialPointTests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ smartseedruntimetest-workflow ] # Temporarily change for testing
  pull_request:
    branches: [ smartseedruntimetest-workflow ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'zulu' # Zulu supports JavaFX, which Evosuite uses.
          java-package: 'jdk+fx'
          cache: 'maven'
      - name: Run tests with Maven
        run: mvn test -Dtest=SmartSeedRuntimeTest#testSpecialPoint* -DfailIfNoTests=false
